### ISSUE TITLE
"Something has fucked up."

### ISSUE THREAD

**Issue by ghost** [yurisuki/osu-install-old#6]
I ran the script and everything seemed to be fine, but after the installation this error message came up:

Something has fucked up.
Log: Oh no, osu! didn't install.

Possibilities are:
You've changed the installation direction.
osu! installer
didn't run.
Some dependencies didn't install.

Try:
Run the script again
Leave the installation direction as it should be (defaultly selected by osu! installer)

If that didn't help try reporting it on GitHub. Thank you. <3

I tried running the script several times and the same thing happens every time. I'm on Manjaro if that makes a difference.

**Comment by yurisuki** [comment]
did osu installer open?

**Comment by ghost** [comment]
No, the installer didn't open.

**Comment by yurisuki** [comment]
> No, the installer didn't open.

do `winetricks --help` show anything rather than an error?

if not, then multilib repository isn't enabled. enable it easily by doing https://wiki.archlinux.org/index.php/Official_repositories#Enabling_multilib and run the script again.

don't worry, multilib packages will be enabled by the script automatically, that's my next goal.

**Comment by ghost** [comment]
winetricks --help showed the intended message and the multilib repository is enabled. I'm still getting the same error.

**Comment by emneo-dev** [comment]
This issue has to be reopened if you still have the problem
